title: Frederik Vosberg
description: >
  A Blog about webdevelopment with PHP, TYPO3, Flow, Neos, Ruby, CSS ...

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fvosberg.github.io"
 
# google_analytics: 'UA-XXXXXXXX-X'

author:
  name: Frederik Vosberg
  email: frederik@rattazonk.com
  uri: https://fvosberg.github.io
  github: fvosberg
  twitter: FrediVosberg
  disqus: fvosberg

markdown: kramdown
#permalink: /post/:title
sass:
  style: compressed

timzone: Europe/Berlin

defaults:
  -
    scope:
      path: ""
    values:
      layout: "null"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "drafts"
    values:
      layout: "post"
