title: Frederik Vosberg
description: >
  A Blog about webdevelopment with PHP, TYPO3, Flow, Neos, Ruby, CSS ...

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.frederikvosberg.de"

google_analytics: 'UA-75974425-1'

author:
  name: Frederik Vosberg
  email: frederik@rattazonk.com
  uri: http://frederikvosberg.de
  github: fvosberg
  twitter: FrediVosberg
  disqus: fvosberg

markdown: kramdown
#permalink: /post/:title
sass:
  style: compressed

timzone: Europe/Berlin

defaults:
  -
    scope:
      path: ""
    values:
      layout: "null"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "drafts"
    values:
      layout: "post"

gems:
  - jekyll-sitemap

exclude:
  - README.html
  - google938354d04c198ece.html
